"""Executor boundary. P1 ships the SIMULATED stub and the receipt/idempotency contract; P3 wires the real rails.

Rail functions are never model tools. The only entry point is `execute`, and it is idempotent: the same
proposal on the same day returns the receipt already issued rather than acting twice.
"""

from __future__ import annotations

import hashlib
import json
from datetime import UTC, datetime

from ..model import ActionProposal, Household, Rail, Receipt, as_utc
from . import idempotency

STUB_LABEL = "P1 stub: no rail wired yet"

# Metadata for the README "What is real" table (regenerated by `household rails` in a later packet).
RAILS: dict[Rail, dict[str, str]] = {
    "ses-email": {
        "name": "Amazon SES email",
        "label": "COMPLETE when EXECUTION_MODE=live and the recipient is a verified identity; SIMULATED otherwise",
        "real": "A real email leaves the account through SES; the MessageId is the provider_ref.",
    },
    "internal-ledger": {
        "name": "Internal household ledger",
        "label": "COMPLETE (internal household ledger, no bank rail)",
        "real": "Double-entry posting between household accounts in this app's ledger. No bank is touched.",
    },
    "stripe-test": {
        "name": "Stripe (test mode)",
        "label": "COMPLETE (test mode) when a test key is present; SIMULATED otherwise",
        "real": "A Stripe test-mode transfer; no real money moves.",
    },
    "official-form": {
        "name": "Official form (prepared, not filed)",
        "label": "PREPARE-ONLY, always",
        "real": "Renders the official form with source quotes for a human to review and file. Never submits.",
    },
    "external-api-readonly": {
        "name": "External read-only lookup",
        "label": "COMPLETE for a live lookup; SIMULATED-replay from a recorded response",
        "real": "Reads public data (recalls, flight status). Never writes anywhere.",
    },
}


def request_digest(proposal: ActionProposal) -> str:
    """sha256 of the canonical proposal JSON, excluding the day-scoped idempotency key."""
    canonical = json.dumps(
        proposal.model_dump(mode="json", exclude={"idempotency_key"}), sort_keys=True, separators=(",", ":")
    )
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def execute(
    proposal: ActionProposal,
    household: Household,
    *,
    execution_mode: str = "simulated",
    now: datetime | None = None,
    grant_id: str | None = None,
) -> Receipt:
    """Return the receipt for this proposal, issuing a SIMULATED one if none exists yet.

    Fills `proposal.idempotency_key` when empty so the recorded action can be matched later.
    `execution_mode` is accepted for the P3 contract; the P1 stub simulates regardless.
    """
    at = as_utc(now) if now is not None else datetime.now(UTC)
    if not proposal.idempotency_key:
        proposal.idempotency_key = idempotency.key(proposal, household.id, at.date().isoformat())
    prior = idempotency.is_duplicate(proposal.idempotency_key, household)
    if prior is not None:
        return prior
    return Receipt(
        id=f"rcpt-{proposal.idempotency_key[:12]}",
        action_id=proposal.id,
        rail=proposal.rail,
        mode="SIMULATED",
        provider_ref=None,
        request_digest=request_digest(proposal),
        response_digest="",
        at=at.isoformat(),
        executed_under_grant=grant_id,
        label_reason=STUB_LABEL,
    )


def record(household: Household, receipt: Receipt) -> None:
    """Attach the receipt to its action record and the household receipt list, exactly once."""
    action = household.action(receipt.action_id)
    if action is None:
        raise KeyError(f"no action record for {receipt.action_id!r}; append the ActionRecord before recording")
    action.receipt = receipt
    if not any(r.id == receipt.id for r in household.receipts):
        household.receipts.append(receipt)
